
-- MySQL Script generated by MySQL Workbench
-- Sun Jan 24 17:44:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant` DEFAULT CHARACTER SET utf8mb4 ;

DROP DATABASE IF EXISTS restaurant;
CREATE DATABASE restaurant;
USE `restaurant` ;

-- -----------------------------------------------------
-- Table `restaurant`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `apellidoMaterno` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `ApellidoPaterno` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `foto` LONGBLOB NULL,
  `edad` INT NOT NULL,
  `password` nvarchar(10) not null,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `restaurant`.`anfitrion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`anfitrion` (
  `idAnfitrion` INT(11) NOT NULL,
  PRIMARY KEY (`idAnfitrion`),
  CONSTRAINT `fk_Anfitrion_Usuario1`
    FOREIGN KEY (`idAnfitrion`)
    REFERENCES `restaurant`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `restaurant`.`comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`comida` (
  `idComida` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(80) CHARACTER SET 'utf8' NOT NULL,
  `raciones` INT(11) NOT NULL,
  `costo` INT(11) NOT NULL,
  `Imagen` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idComida`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `restaurant`.`bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`bebidas` (
  `idComida_bebidas` INT(11) NOT NULL,
  PRIMARY KEY (`idComida_bebidas`),
  CONSTRAINT `fk_bebidas_comida1`
    FOREIGN KEY (`idComida_bebidas`)
    REFERENCES `restaurant`.`comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `restaurant`.`cocinero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`cocinero` (
  `idCocinero` INT(11) NOT NULL,
  PRIMARY KEY (`idCocinero`),
  INDEX `fk_cocinero_Usuario1_idx` (`idCocinero` ASC) ,
  CONSTRAINT `fk_cocinero_Usuario1`
    FOREIGN KEY (`idCocinero`)
    REFERENCES `restaurant`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `restaurant`.`desayunando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`desayunos` (
  `dComida_desayuno` INT(11) NOT NULL,
  PRIMARY KEY (`dComida_desayuno`),
  CONSTRAINT `fk_desayunando_comida1`
    FOREIGN KEY (`dComida_desayuno`)
    REFERENCES `restaurant`.`comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `restaurant`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`gerente` (
  `idGerente` INT(11) NOT NULL,
  `comida_idComida` INT(11) NOT NULL,
  PRIMARY KEY (`idGerente`),
  INDEX `fk_Gerente_Usuario1_idx` (`idGerente` ASC) ,
  INDEX `fk_Gerente_comida1_idx` (`comida_idComida` ASC) ,
  CONSTRAINT `fk_Gerente_Usuario1`
    FOREIGN KEY (`idGerente`)
    REFERENCES `restaurant`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gerente_comida1`
    FOREIGN KEY (`comida_idComida`)
    REFERENCES `restaurant`.`comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `restaurant`.`mesero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`mesero` (
  `idMesero` INT(11) NOT NULL,
  `estado` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMesero`),
  INDEX `fk_mesero_Usuario1_idx` (`idMesero` ASC) ,
  CONSTRAINT `fk_mesero_Usuario1`
    FOREIGN KEY (`idMesero`)
    REFERENCES `restaurant`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `restaurant`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`mesa` (
  `idMesa` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `mesero_idMesero` INT(11) NULL,
  PRIMARY KEY (`idMesa`),
  INDEX `fk_mesa_mesero1_idx` (`mesero_idMesero` ASC),
  CONSTRAINT `fk_mesa_mesero1`
    FOREIGN KEY (`mesero_idMesero`)
    REFERENCES `restaurant`.`mesero` (`idMesero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `restaurant`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`orden` (
  `idOrden` INT(11) NOT NULL AUTO_INCREMENT,
  `idCocinero` INT(11) NOT NULL,
  `importe` INT(11) NOT NULL,
  `idComida` INT(11) NOT NULL,
  `mesa_idMesa` INT(11) NOT NULL,
  PRIMARY KEY (`idOrden`),
  INDEX `fk_orden_cocinero1_idx` (`idCocinero` ASC) ,
  INDEX `fk_orden_comida1_idx` (`idComida` ASC) ,
  INDEX `fk_orden_mesa1_idx` (`mesa_idMesa` ASC) ,
  CONSTRAINT `fk_orden_cocinero1`
    FOREIGN KEY (`idCocinero`)
    REFERENCES `restaurant`.`cocinero` (`idCocinero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_comida1`
    FOREIGN KEY (`idComida`)
    REFERENCES `restaurant`.`comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_mesa1`
    FOREIGN KEY (`mesa_idMesa`)
    REFERENCES `restaurant`.`mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `restaurant`.`postres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`postres` (
  `idComida_postres` INT(11) NOT NULL,
  PRIMARY KEY (`idComida_postres`),
  CONSTRAINT `fk_postres_comida1`
    FOREIGN KEY (`idComida_postres`)
    REFERENCES `restaurant`.`comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
ALTER TABLE `usuario` AUTO_INCREMENT = 10000;


insert into usuario (nombre,apellidoMaterno,apellidoPaterno,puesto,edad) values ('Luis Donaldo','Galloso','Tapia','Mesero',21);
insert into usuario (nombre,apellidoMaterno,apellidoPaterno,puesto,edad) values ('Juan Carlos','Pablo','Santos','Mesero',20);
select * from usuario;